# Generated by Django 4.2.2 on 2023-06-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('RecipeID', models.AutoField(primary_key=True, serialize=False)),
                ('RecipeName', models.CharField(max_length=255)),
                ('Ingredients', models.TextField()),
                ('PreparationSteps', models.TextField()),
                ('DietaryInformation', models.CharField(max_length=255)),
                ('CategoryID', models.IntegerField()),
            ],
        ),
    ]
