# Generated by Django 4.2.2 on 2023-06-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipes',
            table='Recipes',
        ),
    ]
