# Generated by Django 4.2.2 on 2023-06-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_recipes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='RecipeID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
