# Generated by Django 4.2.2 on 2023-06-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_recipes_recipeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='RecipeID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
