# Generated by Django 4.2.2 on 2023-06-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_recipes_recipeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='CategoryID',
        ),
    ]
