# Generated by Django 4.2.2 on 2023-06-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_recipes_recipeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
