# Generated by Django 4.2.2 on 2023-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.AddField(
            model_name='recipes',
            name='CategoryID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
